### ISSUE TITLE
Incorrect compatibility statement for .Net 4,8

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.480#1]
This is not true..
![image](https://user-images.githubusercontent.com/2418812/56112622-88968180-5f53-11e9-8ba1-9c38df4e160b.png)

Windows Versions
https://github.com/Microsoft/dotnet-framework-early-access

The .NET Framework Build 3745 can be installed on the following Windows versions.

Client

    Windows 10, version 1809
    Windows 10, version 1803
    Windows 10, version 1709
    Windows 10, version 1703
    Windows 10, version 1607
    Windows 8.1
    Windows 7 SP1

Server

    Windows Server 2019
    Windows Server, version 1803
    Windows Server, version 1709
    Windows Server 2016
    Windows Server 2012
    Windows Server 2012 R2
    Windows Server 2008 R2 SP1

**Comment by Wagnerp** [comment]
I'll remove, or just say for Windows Server 2008 R2/ 7 SP 1 onwards. I think I wrote it for the first 4.8 build.
